### ISSUE TITLE
Improve favicons

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/website#105]
See #25

**Comment by isimluk** [comment]
Please specify the improvements to be made.

For example, I see we are using openscap-base icon (flavored) now. We may want to consider stock OpenSCAP icon for the website (the blue spiral on white background).

Any other improvements?

**Comment by mpreisler** [comment]
I don't have a clue to be honest. I would like to track a proper graphics designer looking at the favicons in the future. I assume this ticket will be filled with the specific issues once that happens.

**Comment by lhorakov** [comment]
How would you improve that favicon?

**Comment by lhorakov** [comment]
I have thought about this for few days. Firstly I wanted that icon which you already used, the OpenSCAP Base logo graphical part. Then I was thinking about what other possibilities do we have? So I assumed that if we would use blue center line and white backround, as it was in first logo in Old Portal, the visibility would be lower. So I have created the inversion of it, which came from the inverse logo in main header in New Portal. I added it  by Wordpress because he has this function. If you wouldn't like it more that the previous one, I just commented the previous look in header and it can be easily returned. Close or comment please.

**Comment by mpreisler** [comment]
IMO it's worse now. Look's very late 90s :-) But what do I know...

Furthermore, the way you implemented it is problematic, read the original ticket. If the icons are in the root everything is smoother. Some devices ignore the paths in HTML, some devices don't even `GET` the index.html page to read where the icons are, they will go ahead and try to GET `/favicon.ico`.

**Comment by lhorakov** [comment]
I think also that the OpenSCAP Base favicon, the lightblue background, looked better. So back and close.

**Comment by mpreisler** [comment]
So... we are keeping the original favicons I hacked together :-D I can now claim I am an accomplished graphics designer! ;-)

**Comment by lhorakov** [comment]
![mpreislergd](https://cloud.githubusercontent.com/assets/13556662/11086882/afdb2a44-8855-11e5-8f30-983b880d6367.png)
