### ISSUE TITLE
A couple issues on the About Team page

### ISSUE THREAD

**Issue by pbokoc** [OpenSCAP/website#174]
There are a few small issues on the About Team page:

* Some of the bios are written in first person (I am a...), others in third ($name is a ...). I didn't want to just change it as part of the proofreading/editing effort, but you might want to consider bringing them in line.

* The "You" contributor is currently 4th to last, I think that bit should be moved to the end of the list. Also, it would be nice to differentiate that icon, so it's immediately obvious it's not a real person. Maybe replace the silouette with a big question mark?

**Comment by lhorakov** [comment]
First issue about 1st and 3rd person:
- so I checked it and found out that 3:14 people has 1st person : 3rd person, so I changed myself and two other contributors to 3rd person
- I also updated 2 contributors because of some role changes in the team

Second issue:
- I tried to put Question mark icon instead of the avatar but graphically it wasn't the best solution, so I changed Question mark to "You" and I like it much more

Conclusion:
- Both issues were solved, thank you for pointing them out! :)
