### ISSUE TITLE
The different columns on static.open-scap.org page aren't referencable directly

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/website#177]
There are three columns on `static.open-scap.org` page (`API`, `User Manuals`, and `SCAP Security Guides`):

![static_openscap_org_columns](https://cloud.githubusercontent.com/assets/8414918/12585154/0f6b80a4-c44b-11e5-81d8-8488d8763aec.png)
## Current result:

Suppose the use case you want directly to reference just `SCAP Security Guides` column -- it's not possible to do right now (it's necessary to provide `static.open-scap.org` page location, and tell the audience to click on some of the links below the `SCAP Security Guides` column / title).
## Expected result:

The overview of available `SCAP Security Guides` is referencable directly (not sure a dedicated static.open-scap.org subpage wouldn't be required for this though).

**Comment by isimluk** [comment]
I think the purpose of static index is just to be an index, not a new website with couple of non-wordpress pages. Anyway, I am afraid there are no backups of the static.open-scap.org...?

I like the http://www.open-scap.org/security-policies/choosing-policy/ page when referencing people to the vast possibilities of the content. The problem is that the choosing-policy page contains the list at the very bottom.

Perhaps we can revive the idea of having  'All Policies ' page, that we started with. This idea has been scratched during the portal creation process, because nobody remembered, why it was there (when I was on holidays). :-))

**Comment by iankko** [comment]
> Perhaps we can revive the idea of having 'All Policies ' page, that we started with.

Maybe we could create a dedicated "All Policies" page from the "Security policies available in the SCAP Security Guide" section?

The motivation is to have a page, where:
* all currently present SSG products would be listed,
* all profiles for these products would be listed.

The former isn't possible to do right now (on static.open-scap.org page) -- it's possible to reference HTML guide for concrete product (but in that case there won't be overview of remaining products), or it's possible to reference ```static.open-scap.org``` -- in this case there under Documentation are products, but not the HTML guides for the profiles.

I would vote +1 for re-introduction of "All Policies" page.

**Comment by matusmarhefka** [comment]
We discussed and we are not convinced there are use cases for this feature.
