### ISSUE TITLE
Missing links to download OpenSCAP Workbench for Windows and Mac

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/website#40]

**Comment by isimluk** [comment]
Tentatively assigning 1.0 milestone, can be moved to 2.0.

**Comment by mpreisler** [comment]
The problem is that the link will change with each new workbench release. Here's an idea how to solve this.

I create 2 redirects on the portal site:
/tools/scap-workbench/download-win32 -> win32 MSI installer
/tools/scap-workbench/download-osx -> OSX image

We use these redirects on the site. I will add a task to change them to the release guide of SCAP Workbench.

Does anybody see any issues with this approach?

**Comment by jan-cerny** [comment]
I have one question: Is there a requirement to download older versions of the SCAP Workbench for Windows/Mac ? Does somebody need to download an older version instead of the updated?

**Comment by mpreisler** [comment]
> I have one question: Is there a requirement to download older versions of the SCAP Workbench for Windows/Mac ? Does somebody need to download an older version instead of the updated?

No, why?

**Comment by isimluk** [comment]
For 1.0 I think we can hard-code the URLs (and create 2.0 ticket for generic solution). What do you think?

**Comment by jan-cerny** [comment]
@mpreisler Then OK, so we needn't create a solution for direct downloads of older versions.
@isimluk I agree.

**Comment by mpreisler** [comment]
- made the redirects
  - http://www-rhopenscap.rhcloud.com/tools/scap-workbench/download-win32
  - http://www-rhopenscap.rhcloud.com/tools/scap-workbench/download-osx
- updated http://www-rhopenscap.rhcloud.com/tools/scap-workbench/ with the links
- updated http://www-rhopenscap.rhcloud.com/get-it/ with the links

I think it makes perfect sense to only link the latest version for Windows and OSX. If people want old versions they can get them on github but I think that's a minority and making the portal more complex and more difficult to navigate is not a good trade-off.
