### ISSUE TITLE
Contribute Page -- Link names color under the "Select your favourite language"  does not match color of other links

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/website#76]
Compare the light blue color e.g. in "OpenSCAP Base" link with the light purple color in in the section above (see image below):

![contribute_choose_language_link_colors](https://cloud.githubusercontent.com/assets/8414918/10224356/c5591614-685d-11e5-93d1-1ee8cc9e4079.png)

**Comment by lhorakov** [comment]
That's because there are 3 types of links:
- Classic Blue Links (Used everywhere where it can be used and it's visible)
- Light Blue Links (Used everywhere where the Classic Blue Links aren't visible)
- Red Links (Used where no blue links can be used becuase of visibility)

Here we have white background ->  Classic Blue Links
