### ISSUE TITLE
Contribute page - Developer - move away "Bug fixing" text

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/website#79]
I don't like that "Developer" contains long text about bug fixing. I would put the text to some document "How to contribute", but not here. 

I think the text here should be replaced by a text similar to for example *Testing enthusiast – Bug hunter* text.

What do you think about it?

**Comment by msrubar** [comment]
I agree. As a developer wanting to fix a bug or want to start contribute I wouldn't be search for this kind of information on the portal. 

I wrote a little [how to contribute](https://github.com/lhorakov/openscap-doc/blob/master/contribute.adoc) a few weeks back but I didn't continue working on it because of other priorities. It might be helpful or could build on ...

**Comment by mpreisler** [comment]
This is milestone 2 I think.

PS: Please insert links into the issue descriptions. It saves a lot of time when people can just click and see what you are talking about.

**Comment by isimluk** [comment]
@jan-cerny , I think this has been improved significantly over time. What do you think? Can we close this?

**Comment by jan-cerny** [comment]
@isimluk I don't agree with you. At the "developer" section, there is still text about bug fixing and code reviewing. This text doesn't follow the purpose of this page. I suggest writing new text which will be similar to other sections of this page. The text should describe the developer role and why we need new developers in our projects. The current text should go to contribute.adoc.

This issue description is still completely applicable. I vote against closing this.

**Comment by iankko** [comment]
@jan-cerny 
> @isimluk I don't agree with you. At the "developer" section, there is still text about bug fixing and code reviewing. This text doesn't follow the purpose of this page. I suggest writing new text which will be similar to other sections of this page. The text should describe the developer role and why we need new developers in our projects. The current text should go to contribute.adoc.

Like already said at some of our previous meetings, would all of the OpenSCAP/* GH projects currently have information how to contribute to them, then I would agree this information is redundant.

But since this is not the case, IMHO that developer section text should remain there. The purpose of that text is to share some basic information like indentation customs, how to create a good PR request etc. IMHO this information is applicable enough to all of the projects.

If I would be a starter for OpenSCAP project I would appreciate the information that all projects are hosted on GitHub and that I first need to get familiar with git- and GitHub- workflow to be able to contribute right away from the start.
